### ISSUE TITLE
Scraping additional info from glassdoor

### ISSUE THREAD

**Issue by ghost** [mguideng/rvest-scrape-glassdoor#1]
Hi I was going through your materials and was wondering is there any way to scrape the rating for each comment (no. of stars) ?. Thanks

**Comment by mguideng** [comment]
> Hi I was going through your materials and was wondering is there any way to scrape the rating for each comment (no. of stars) ?. Thanks

Great addition, XswordcraftX! Yes - it's doable. I'll incorporate.
